# Use root/toor as user/password credentials
version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_DATABASE: instadukan
        # MONGO_INITDB_ROOT_USERNAME: root
        # MONGO_INITDB_ROOT_PASSWORD: toor 
    # command:
        # - '--auth'
    ports:
        - 27017-27019:27017-27019
    volumes:
        - ./storage:/data/db
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
        - local
  adminer:
    image: mongoclient/mongoclient
    restart: always
    ports:
      - 8889:3000
    networks:
        - local
networks:
    local:
        external: true