# Use root/toor as user/password credentials
version: '3.1'
services:
  mysql-db:
    image: mariadb
    restart: always
    environment:
        MARIADB_ROOT_PASSWORD: toor
    ports:
        - 3306:3306
        - 33060:33060
    volumes:
        - ./storage:/var/lib/mysql
    networks:
        - local
networks:
    local:
        external: true