# Use root/toor as user/password credentials
version: '3.1'
services:
  memcached:
    image: memcached
    restart: always
    ports:
        - 11211:11211
    networks:
        - local
networks:
    local:
        external: true