version: '3.1'
services:
   adminer:
    image: dockette/adminer:full
    restart: always
    environment:
        UPLOAD: 4096M
    ports:
      - 8080:80
    networks:
        - local
networks:
    local:
        external: true