# Use root/toor as user/password credentials
version: '3.1'

services:
    strapi:
        image: marcopeg/docker-vacuum
        networks:
            - local
networks:
    local:
        external: true